packages:
  - apps/*
  - packages/*

allowBuilds:
  "@biomejs/biome": true
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - lefthook
  - sharp
  - workerd
